[package]
name = "aoc-2020-rust"
version = "0.1.0"
authors = ["Jason Diamond <jason@diamond.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap ="2"
itertools = "0.9.0"
lazy_static = "1"
regex = "1"
